### ISSUE TITLE
Not an issue a Kudos! and hoping for more RP2040 projects

### ISSUE THREAD

**Issue by anglerfish27** [stienman/Raspberry-Pi-Pico-PIO-LCD-Driver#1]
Thank you for your amazing work with the WaveShare LCD's I use them quite a bit and I've found that with such limited RAM displaying 65K color images on anything remotely large screen >3inches, is just chokes. The "sample code for their products is horrendous and is not even complete in some cases for some products (not screens). I program in in C/C++ and not python, which is what WS share seems to love to give with its examples. Very frustrating. Even their DS 3231 RTC C code was amazingly terrible. I plan to re-write it myself one of these days. I don't use Arduino. Just C/C++ and eventually ASM/PIO. I have a book on it but I haven't cracked it open yet. Do you have any recommendations for PIO on RP2040? 

Again thank for your hard work, would be neat to see you do more Pico projects that rival some of the common things people do with Picos, especially  Pico W's with wireless. Looks the the C/C++ implementation of wireless is a hot mess. Sure looks simpler in python!

I would love to pick your brain about ways to save RAM on PICO for displaying 65K color images on displays frome 240X320 and higher. How that can be done with  minimizing RAM usage and still loading images. Hopefully you'll ping me sometime. I've also wondered if there is a way somehow to use some of the onboard storage (some picos come up to 16MB) and trick the MCU into thinking some of it RAM virtually eliminating many problems with OOM conditions for images.  I'm nowhere at your level but I am going to tear apart your code bit by bit with my logic analzyer and waveshare board and try to follow along. I'm glad I stumbled across your article in Hackaday! Keep the Pico Alive, I bet you could write some amazing wireless stuff!!

Cheers from Florida,
Anglerfish

**Comment by stienman** [comment]
Sorry I missed this!  I didn't write this code, it is a copy of
https://dmitry.gr/?r=06.%20Thoughts&proj=09.ComplexPioMachines

And I agree, this is great work on his part!
